spring:
  application:
    name: hjpark-onboarding
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    root: INFO
    com.hjpark.survey: DEBUG

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

springdoc:
  swagger-ui:
    groups-order: DESC
    operations-sorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api-docs