-- 설문조사 테이블
CREATE TABLE survey (
                        survey_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        survey_name VARCHAR(255) NOT NULL,
                        description TEXT,
                        create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_survey_name ON survey(survey_name);

-- 질문 테이블 (ENUM 타입 유지)
CREATE TABLE question (
                          question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          survey_id BIGINT NOT NULL,
                          sequence SMALLINT NOT NULL,
                          question_name VARCHAR(255) NOT NULL,
                          description TEXT,
                          question_type VARCHAR(20) NOT NULL CHECK (
                                  question_type IN ('SHORT_ANSWER', 'LONG_ANSWER', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE')
                              ),
                          required BOOLEAN DEFAULT FALSE,
                          create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          FOREIGN KEY (survey_id) REFERENCES survey(survey_id) ON DELETE CASCADE
);

CREATE INDEX idx_question_survey ON question(survey_id);

-- 질문 옵션 테이블
CREATE TABLE question_option (
                                 option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 question_id BIGINT NOT NULL,
                                 option_text VARCHAR(255) NOT NULL,
                                 sequence INT NOT NULL,
                                 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 FOREIGN KEY (question_id) REFERENCES question(question_id) ON DELETE CASCADE
);

CREATE INDEX idx_option_question ON question_option(question_id);

-- 응답 테이블
CREATE TABLE survey_response (
                                 response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 survey_id BIGINT NOT NULL,
                                 respondent_id VARCHAR(255),
                                 status VARCHAR(50) CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
                                 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 FOREIGN KEY (survey_id) REFERENCES survey(survey_id) ON DELETE CASCADE
);

CREATE INDEX idx_response_survey ON survey_response(survey_id);

-- 응답 항목 테이블
CREATE TABLE response_item (
                               item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               response_id BIGINT NOT NULL,
                               question_id BIGINT NOT NULL,
                               text_value TEXT,
                               option_id BIGINT,
                               create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               FOREIGN KEY (response_id) REFERENCES survey_response(response_id) ON DELETE CASCADE,
                               FOREIGN KEY (question_id) REFERENCES question(question_id),
                               FOREIGN KEY (option_id) REFERENCES question_option(option_id),
                               CONSTRAINT uc_response_item UNIQUE (response_id, question_id, option_id)
);

CREATE INDEX idx_item_response ON response_item(response_id);
CREATE INDEX idx_item_question ON response_item(question_id);