spring:
  application:
    name: seonghun-onboarding

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: demo

  jpa:
    hibernate:
      ddl-auto: create # spring ? ??? ??? db ??
    properties:
      hibernate:
        format_sql: true
        show_sql: true

