name: PR Build Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  find-projects:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}
    steps:
      - uses: actions/checkout@v3

      - name: Find projects with gradlew
        id: set-projects
        shell: bash
        run: |
          # Find all gradlew files and extract their paths
          projects=$(find ./project -name "gradlew" -type f -exec dirname {} \; | sed 's|^./project/||')
          
          # Create proper JSON array
          echo "projects=$(echo $projects | jq -R 'split(" ")' -c)" >> $GITHUB_OUTPUT
          echo "Found projects: $(echo $projects | jq -R 'split(" ")' -c)"

  build-all:
    needs: find-projects
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Get all projects
        run: |
          echo "Building projects:"
          echo '${{ needs.find-projects.outputs.projects }}'

      - name: Make all gradlew files executable
        run: |
          for project in $(echo '${{ needs.find-projects.outputs.projects }}' | jq -r '.[]'); do
            echo "Making gradlew executable for $project"
            chmod +x ./project/$project/gradlew
          done

      - name: Build all projects
        id: build
        run: |
          success=true
          failed_projects=()
          
          for project in $(echo '${{ needs.find-projects.outputs.projects }}' | jq -r '.[]'); do
            echo "Building $project..."
          
            cd $GITHUB_WORKSPACE/project/$project
            if ./gradlew clean build; then
              echo "✅ Build succeeded for $project"
            else
              echo "❌ Build failed for $project"
              failed_projects+=("$project")
              success=false
            fi
            cd $GITHUB_WORKSPACE
          done
          
          if [ "$success" = false ]; then
            echo "::error::Failed projects: ${failed_projects[@]}"
            exit 1
          fi
